# -*- coding: utf-8 -*-
"""Lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xEUVho1VEZMfhSsoWIVVkmFpoNJD1Mi
"""

!wget https://github.com/Horea94/Fruit-Images-Dataset/archive/refs/heads/master.zip -O fruits.zip
!unzip -q fruits.zip
print('Đã tải và giải nén xong bộ dữ liệu!')

### 2. Tiền xử lý và Lọc 10 loại hoa quả
**Vai trò**: Chuẩn bị dữ liệu sạch và chia tập dữ liệu.
**Cách hoạt động**: Lọc 10 lớp mục tiêu, thực hiện Augmentation (xoay, lật) và chia tỉ lệ Train/Val (80/20).

import os
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

stats = ((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
fruit_transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(*stats)
])

data_dir = 'Fruit-Images-Dataset-master/Training'
full_dataset = ImageFolder(root=data_dir, transform=fruit_transform)
selected_classes = ['Apple Braeburn', 'Banana', 'Cherry 1', 'Grape White', 'Kiwi', 'Lemon', 'Orange', 'Peach', 'Pear', 'Strawberry']
class_to_idx = {cls: i for i, cls in enumerate(selected_classes)}

filtered_samples = [(p, class_to_idx[full_dataset.classes[t]]) for p, t in full_dataset.samples if full_dataset.classes[t] in selected_classes]

fruit_dataset = ImageFolder(root=data_dir, transform=fruit_transform)
fruit_dataset.samples = filtered_samples
fruit_dataset.targets = [s[1] for s in filtered_samples]
fruit_dataset.classes = selected_classes

train_size = int(0.8 * len(fruit_dataset))
val_size = len(fruit_dataset) - train_size
train_set, val_set = random_split(fruit_dataset, [train_size, val_size])

classes = selected_classes
print(f'Đã sẵn sàng {len(fruit_dataset)} ảnh thuộc 10 loại quả.')

### 3. Định nghĩa mô hình CNN và Hàm huấn luyện
**Vai trò**: Thiết kế cấu trúc mạng thần kinh và logic học tập.
**Cách hoạt động**: Sử dụng SimpleCNN với 2 lớp Conv2d. Hàm huấn luyện ghi lại lịch sử để so sánh Batch Size.

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, 10)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.flatten(x)
        x = self.dropout(self.relu(self.fc1(x)))
        x = self.fc2(x)
        return x

def train_model(batch_size, epochs=5):
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False)
    net = SimpleCNN().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(net.parameters(), lr=0.001)
    history = {'train_loss': [], 'val_acc': []}
    for epoch in range(epochs):
        net.train()
        running_loss = 0.0
        for imgs, lbls in train_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            optimizer.zero_grad()
            loss = criterion(net(imgs), lbls)
            loss.backward(); optimizer.step()
            running_loss += loss.item()
        history['train_loss'].append(running_loss / len(train_loader))
        net.eval()
        correct, total = 0, 0
        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                _, pred = torch.max(net(imgs), 1)
                total += lbls.size(0); correct += (pred == lbls).sum().item()
        history['val_acc'].append(100 * correct / total)
    return net, history

### 4. So sánh hiệu năng và Ma trận nhầm lẫn
**Vai trò**: Đánh giá sự khác biệt giữa các cấu hình Batch Size.
**Cách hoạt động**: Vẽ đồ thị Loss/Accuracy và Confusion Matrix side-by-side.

model_32, history_32 = train_model(32)
model_64, history_64 = train_model(64)

plt.figure(figsize=(14, 5))
plt.subplot(1, 2, 1)
plt.plot(history_32['train_loss'], label='Batch 32'); plt.plot(history_64['train_loss'], label='Batch 64')
plt.title('Loss'); plt.legend()
plt.subplot(1, 2, 2)
plt.plot(history_32['val_acc'], label='Batch 32'); plt.plot(history_64['val_acc'], label='Batch 64')
plt.title('Accuracy (%)'); plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns

def evaluate(model, loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for imgs, lbls in loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            outputs = model(imgs)
            _, predicted = torch.max(outputs, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(lbls.cpu().numpy())
    return all_labels, all_preds

# 5. Đánh giá trên tập Validation của dữ liệu Hoa quả
val_loader_eval = DataLoader(val_fruits, batch_size=64, shuffle=False)
y_true, y_pred = evaluate(final_model, val_loader_eval)

# Vẽ Confusion Matrix cho hoa quả
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=classes, yticklabels=classes, cmap='YlOrBr')
plt.xlabel('Dự đoán')
plt.ylabel('Thực tế')
plt.title('Confusion Matrix - Real Fruit Dataset')
plt.show()

final_model.eval()
# Đảm bảo dùng danh sách nhãn hoa quả
fruit_classes = ['Apple Braeburn', 'Banana', 'Cherry 1', 'Grape White', 'Kiwi', 'Lemon', 'Orange', 'Peach', 'Pear', 'Strawberry']

dataiter = iter(DataLoader(val_fruits, batch_size=10, shuffle=True))
images, labels = next(dataiter)
with torch.no_grad():
    outputs = final_model(images.to(device))
    _, predicted = torch.max(outputs, 1)

print('Hiển thị 10 mẫu dự đoán hoa quả thực tế:')
imshow(torchvision.utils.make_grid(images))
print('Thực tế: ', [fruit_classes[labels[j]] for j in range(10)])
print('Dự đoán: ', [fruit_classes[predicted[j]] for j in range(10)])

print('\n' + '='*30)
print('--- PHÂN TÍCH LỖI CHI TIẾT (Fruit Error Analysis) ---')
print('1. Nhầm lẫn dựa trên màu sắc: Lemon và Banana có màu vàng tương tự.')
print('2. Hình dáng hình học: Orange, Peach và Apple đều có hình tròn.')
print('3. Đặc trưng riêng: Strawberry và Kiwi có kết cấu vỏ đặc trưng nên ít nhầm lẫn.')
print('='*30)

# Hiển thị 10 mẫu dự đoán và Phân tích lỗi (Error Analysis)
final_model.eval()
# Sử dụng đúng danh sách nhãn hoa quả
fruit_classes = ['Apple Braeburn', 'Banana', 'Cherry 1', 'Grape White', 'Kiwi', 'Lemon', 'Orange', 'Peach', 'Pear', 'Strawberry']

dataiter = iter(DataLoader(val_fruits, batch_size=10, shuffle=True))
images, labels = next(dataiter)

with torch.no_grad():
    outputs = final_model(images.to(device))
    _, predicted = torch.max(outputs, 1)

print('Hiển thị 10 mẫu dự đoán hoa quả thực tế:')
imshow(torchvision.utils.make_grid(images))
print('Thực tế: ', [fruit_classes[labels[j]] for j in range(10)])
print('Dự đoán: ', [fruit_classes[predicted[j]] for j in range(10)])

print('\n' + '='*30)
print('--- PHÂN TÍCH LỖI CHI TIẾT (Fruit Error Analysis) ---')
print('1. Nhầm lẫn dựa trên màu sắc: Lemon và Banana có màu vàng tương tự.')
print('2. Hình dáng hình học: Orange, Peach và Apple đều có hình tròn.')
print('3. Đặc trưng riêng: Strawberry và Kiwi có kết cấu vỏ đặc trưng nên ít nhầm lẫn.')
print('='*30)

# Hiển thị 10 mẫu dự đoán và Phân tích lỗi (Error Analysis)
final_model.eval()
# Sử dụng đúng danh sách nhãn hoa quả
fruit_classes = ['Apple Braeburn', 'Banana', 'Cherry 1', 'Grape White', 'Kiwi', 'Lemon', 'Orange', 'Peach', 'Pear', 'Strawberry']

dataiter = iter(DataLoader(val_fruits, batch_size=10, shuffle=True))
images, labels = next(dataiter)

with torch.no_grad():
    outputs = final_model(images.to(device))
    _, predicted = torch.max(outputs, 1)

print('Hiển thị 10 mẫu dự đoán hoa quả thực tế:')
imshow(torchvision.utils.make_grid(images))
print('Thực tế: ', [fruit_classes[labels[j]] for j in range(10)])
print('Dự đoán: ', [fruit_classes[predicted[j]] for j in range(10)])

print('\n' + '='*30)
print('--- PHÂN TÍCH LỖI CHI TIẾT (Fruit Error Analysis) ---')
print('1. Nhầm lẫn dựa trên màu sắc: Lemon và Banana có màu vàng tương tự.')
print('2. Hình dáng hình học: Orange, Peach và Apple đều có hình tròn.')
print('3. Đặc trưng riêng: Strawberry và Kiwi có kết cấu vỏ đặc trưng nên ít nhầm lẫn.')
print('='*30)

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Subset
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

# 1. Tiền xử lý dữ liệu Hoa quả (Fruit Preprocessing)
import os
from torchvision.datasets import ImageFolder
from torch.utils.data import random_split

stats = ((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))

fruit_transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(*stats)
])

# Đường dẫn thư mục Training hoa quả
data_dir = 'Fruit-Images-Dataset-master/Training'
full_fruit_dataset = ImageFolder(root=data_dir, transform=fruit_transform)

# Lọc 10 lớp mục tiêu
selected_classes = ['Apple Braeburn', 'Banana', 'Cherry 1', 'Grape White', 'Kiwi', 'Lemon', 'Orange', 'Peach', 'Pear', 'Strawberry']
class_to_idx = {cls: i for i, cls in enumerate(selected_classes)}

filtered_samples = []
for path, target in full_fruit_dataset.samples:
    class_name = full_fruit_dataset.classes[target]
    if class_name in selected_classes:
        filtered_samples.append((path, class_to_idx[class_name]))

# Tạo dataset hoa quả đã lọc
fruit_dataset = ImageFolder(root=data_dir, transform=fruit_transform)
fruit_dataset.samples = filtered_samples
fruit_dataset.targets = [s[1] for s in filtered_samples]
fruit_dataset.classes = selected_classes

# Chia tập Train và Validation (80/20)
train_size = int(0.8 * len(fruit_dataset))
val_size = len(fruit_dataset) - train_size
train_set, val_set = random_split(fruit_dataset, [train_size, val_size])

classes = selected_classes
print(f'Đã sẵn sàng {len(fruit_dataset)} ảnh thuộc 10 loại hoa quả thực tế!')

def imshow(img):
    img = img * 0.2 + 0.5 # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

# Show 10 sample images
dataiter = iter(DataLoader(train_set, batch_size=10, shuffle=True))
images, labels = next(dataiter)

print('Displaying 10 sample images:')
imshow(torchvision.utils.make_grid(images))
print(' '.join(f'{classes[labels[j]]:5s}' for j in range(10)))

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        # Conv2d → ReLU → MaxPool
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.relu1 = nn.ReLU()
        self.pool1 = nn.MaxPool2d(2, 2)

        # Conv2d → ReLU → MaxPool
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(2, 2)

        # Flatten → Linear → ReLU → Dropout → Linear → Softmax
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.relu3 = nn.ReLU()
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(128, 10)
        # Note: Softmax is typically included in CrossEntropyLoss during training

    def forward(self, x):
        x = self.pool1(self.relu1(self.conv1(x)))
        x = self.pool2(self.relu2(self.conv2(x)))
        x = self.flatten(x)
        x = self.dropout(self.relu3(self.fc1(x)))
        x = self.fc2(x)
        return x

model = SimpleCNN().to(device)
print(model)

def train_model(batch_size, epochs=5):
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False)

    net = SimpleCNN().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(net.parameters(), lr=0.001)

    # Dictionary để lưu lịch sử
    history = {'train_loss': [], 'val_acc': []}

    print(f'\nTraining with Batch Size: {batch_size}')
    for epoch in range(epochs):
        net.train()
        running_loss = 0.0
        for i, (images, labels) in enumerate(train_loader):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = net(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()

        history['train_loss'].append(running_loss / len(train_loader))

        # Tính Validation Accuracy mỗi epoch
        net.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = net(images)
                _, predicted = torch.max(outputs.data, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        acc = 100 * correct / total
        history['val_acc'].append(acc)
        print(f'Epoch {epoch+1} - Loss: {history["train_loss"][-1]:.4f} - Val Acc: {acc:.2f}%')

    return net, history

# Thực hiện huấn luyện cho 2 model
model_32, history_32 = train_model(32, epochs=5)
model_64, history_64 = train_model(64, epochs=5)

def evaluate(model, test_loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return all_labels, all_preds

import matplotlib.pyplot as plt

# 5. Vẽ đồ thị Training & Validation (Phân tích kết quả)
plt.figure(figsize=(12, 5))

# Đồ thị Loss
plt.subplot(1, 2, 1)
plt.plot(history['train_loss'], label='Training Loss', marker='o')
plt.plot(history['val_loss'], label='Validation Loss', marker='x')
plt.title('Training & Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# Đồ thị Accuracy
plt.subplot(1, 2, 2)
plt.plot(history['train_acc'], label='Training Accuracy', marker='o', color='green')
plt.plot(history['val_acc'], label='Validation Accuracy', marker='x', color='red')
plt.title('Training & Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

print('--- PHÂN TÍCH CHI TIẾT 3 ẢNH LỖI CHUNG ---')
plt.figure(figsize=(12, 4))
for i, err in enumerate(errors):
    plt.subplot(1, 3, i + 1)
    # Unnormalize: img * std + mean
    img = err['image'] * 0.5 + 0.5
    plt.imshow(np.transpose(img.numpy(), (1, 2, 0)))
    plt.title(f"Thực tế: {classes[err['true']]}\nM32: {classes[err['pred1']]}\nM64: {classes[err['pred2']]}")
    plt.axis('off')
plt.tight_layout()
plt.show()

print('\nLý do chính:')
print('1. Cả 3 ảnh đều là quả Đào bị nhận nhầm thành Táo Braeburn.')
print('2. Sự tương đồng về màu sắc (đỏ-vàng) và hình dáng tròn khiến CNN ở độ phân giải 32x32 khó phân biệt.')

def find_common_misclassifications(model1, model2, loader):
    model1.eval()
    model2.eval()
    common_errors = []

    with torch.no_grad():
        for images, labels in loader:
            images_dev = images.to(device)
            out1 = model1(images_dev)
            out2 = model2(images_dev)
            _, pred1 = torch.max(out1, 1)
            _, pred2 = torch.max(out2, 1)

            pred1 = pred1.cpu()
            pred2 = pred2.cpu()

            # Tìm các vị trí mà cả 2 model đều sai so với labels
            mask = (pred1 != labels) & (pred2 != labels)
            if mask.any():
                indices = torch.where(mask)[0]
                for idx in indices:
                    common_errors.append({
                        'image': images[idx],
                        'true': labels[idx].item(),
                        'pred1': pred1[idx].item(),
                        'pred2': pred2[idx].item()
                    })
    return common_errors

# Kiểm tra trên toàn bộ tập validation
val_loader_full = DataLoader(val_set, batch_size=64, shuffle=False)
errors = find_common_misclassifications(model_32, model_64, val_loader_full)

if len(errors) == 0:
    print('Chúc mừng! Không có ảnh nào bị cả hai model dự đoán sai trên tập Validation.')
else:
    print(f'Tìm thấy {len(errors)} ảnh bị cả hai model dự đoán sai:')
    plt.figure(figsize=(15, 5 * ((len(errors)//5) + 1)))
    for i, err in enumerate(errors[:10]): # Hiển thị tối đa 10 mẫu lỗi đầu tiên
        plt.subplot((len(errors)//5) + 1, 5, i + 1)
        img = err['image'] * 0.2 + 0.5
        plt.imshow(np.transpose(img.numpy(), (1, 2, 0)))
        plt.title(f"True: {classes[err['true']]}\nM32: {classes[err['pred1']]}\nM64: {classes[err['pred2']]}", fontsize=9)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

def visualize_comparison(model1, model2, loader, num_images=10):
    model1.eval()
    model2.eval()
    dataiter = iter(loader)
    images, labels = next(dataiter)

    images_dev = images[:num_images].to(device)
    with torch.no_grad():
        out1 = model1(images_dev)
        out2 = model2(images_dev)
        _, pred1 = torch.max(out1, 1)
        _, pred2 = torch.max(out2, 1)

    plt.figure(figsize=(20, 10))
    for i in range(num_images):
        plt.subplot(2, 5, i + 1)
        img = images[i] * 0.2 + 0.5  # unnormalize
        plt.imshow(np.transpose(img.numpy(), (1, 2, 0)))

        color1 = 'green' if pred1[i] == labels[i] else 'red'
        color2 = 'blue' if pred2[i] == labels[i] else 'orange'

        title_text = f'True: {classes[labels[i]]}\nM32: {classes[pred1[i]]}\nM64: {classes[pred2[i]]}'
        plt.title(title_text, fontsize=10, color='black')
        plt.axis('off')

    plt.tight_layout()
    plt.show()

# Hiển thị so sánh trên tập validation
compare_loader = DataLoader(val_set, batch_size=10, shuffle=True)
visualize_comparison(model_32, model_64, compare_loader)

print('--- ĐÁNH GIÁ MODEL BATCH SIZE 64 TRÊN TẬP TEST ---')
test_loader = DataLoader(val_set, batch_size=64, shuffle=False)
y_true_test, y_pred_test = evaluate(model_64, test_loader)

# Vẽ Confusion Matrix
plt.figure(figsize=(10, 8))
cm_test = confusion_matrix(y_true_test, y_pred_test)
sns.heatmap(cm_test, annot=True, fmt='d', xticklabels=classes, yticklabels=classes, cmap='Greens')
plt.xlabel('Dự đoán')
plt.ylabel('Thực tế')
plt.title('Confusion Matrix - Model 64 (Test Set)')
plt.show()

# In báo cáo chi tiết
from sklearn.metrics import classification_report
print(classification_report(y_true_test, y_pred_test, target_names=classes))

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 6))

# So sánh Loss
plt.subplot(1, 2, 1)
plt.plot(history_32['train_loss'], label='Batch 32 Loss', marker='o')
plt.plot(history_64['train_loss'], label='Batch 64 Loss', marker='s')
plt.title('Training Loss Comparison')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# So sánh Accuracy
plt.subplot(1, 2, 2)
plt.plot(history_32['val_acc'], label='Batch 32 Val Acc', marker='o')
plt.plot(history_64['val_acc'], label='Batch 64 Val Acc', marker='s')
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report

# Báo cáo cho Model Batch Size 32
print('--- BÁO CÁO PHÂN LOẠI: BATCH SIZE 32 ---')
print(classification_report(y_true_32, y_pred_32, target_names=classes))

print('\n' + '='*60 + '\n')

# Báo cáo cho Model Batch Size 64
print('--- BÁO CÁO PHÂN LOẠI: BATCH SIZE 64 ---')
print(classification_report(y_true_64, y_pred_64, target_names=classes))

def get_predictions(model, loader):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs, 1)
            all_preds.extend(predicted.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return all_labels, all_preds

val_loader_compare = DataLoader(val_set, batch_size=64, shuffle=False)

# Lấy dự đoán cho cả 2 model
y_true_32, y_pred_32 = get_predictions(model_32, val_loader_compare)
y_true_64, y_pred_64 = get_predictions(model_64, val_loader_compare)

# Vẽ đồ thị so sánh
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

cm32 = confusion_matrix(y_true_32, y_pred_32)
sns.heatmap(cm32, annot=True, fmt='d', xticklabels=classes, yticklabels=classes, cmap='Blues', ax=ax1)
ax1.set_title('Confusion Matrix - Batch Size 32')
ax1.set_xlabel('Predicted')
ax1.set_ylabel('True')

cm64 = confusion_matrix(y_true_64, y_pred_64)
sns.heatmap(cm64, annot=True, fmt='d', xticklabels=classes, yticklabels=classes, cmap='Greens', ax=ax2)
ax2.set_title('Confusion Matrix - Batch Size 64')
ax2.set_xlabel('Predicted')
ax2.set_ylabel('True')

plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 6))

# So sánh Loss
plt.subplot(1, 2, 1)
plt.plot(history_32['train_loss'], label='Batch 32 Loss', marker='o')
plt.plot(history_64['train_loss'], label='Batch 64 Loss', marker='s')
plt.title('Training Loss Comparison')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# So sánh Accuracy
plt.subplot(1, 2, 2)
plt.plot(history_32['val_acc'], label='Batch 32 Val Acc', marker='o')
plt.plot(history_64['val_acc'], label='Batch 64 Val Acc', marker='s')
plt.title('Validation Accuracy Comparison')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

"""### 1. Tải và Giải nén Dữ liệu
**Vai trò**: Tải bộ dữ liệu hình ảnh hoa quả từ GitHub về môi trường Colab.
**Cách hoạt động**: Sử dụng lệnh `!wget` để tải file zip và `!unzip` để giải nén. Dữ liệu này chứa hàng ngàn ảnh hoa quả được chia theo thư mục lớp.

### 2. Tiền xử lý và Lọc dữ liệu
**Vai trò**: Chuẩn bị dữ liệu để đưa vào mô hình Deep Learning.
**Cách hoạt động**:
- **Transforms**: Thay đổi kích thước ảnh về 32x32, thực hiện xoay/lật ngẫu nhiên để tăng độ đa dạng (Augmentation) và chuẩn hóa màu sắc.
- **Filtering**: Chỉ lọc ra 10 loại hoa quả mục tiêu từ bộ dữ liệu gốc khổng lồ.
- **Splitting**: Chia dữ liệu thành 80% để huấn luyện (Train) và 20% để kiểm tra (Validation).

### 3. Định nghĩa Kiến trúc Mô hình CNN
**Vai trò**: Xây dựng bộ não cho hệ thống nhận diện.
**Cách hoạt động**: Sử dụng mạng thần kinh nhân tạo tích chập (Convolutional Neural Network - CNN) với:
- 2 lớp Tích chập (Conv2d) để trích xuất đặc trưng hình dạng/màu sắc.
- Lớp Dropout để chống học vẹt (overfitting).
- Lớp Tuyến tính (Linear) cuối cùng để phân loại vào 10 nhóm hoa quả.

### 4. Huấn luyện Mô hình (Training)
**Vai trò**: Dạy mô hình cách nhận diện hoa quả thông qua dữ liệu.
**Cách hoạt động**: Sử dụng thuật toán tối ưu hóa **Adam** và hàm mất mát **CrossEntropyLoss**. Mô hình sẽ lặp qua dữ liệu nhiều lần (Epochs), tính toán sai số và cập nhật các trọng số bên trong để giảm thiểu lỗi.

### 5. Đánh giá và Phân tích Lỗi
**Vai trò**: Kiểm tra xem mô hình học tốt đến mức nào và nó hay sai ở đâu.
**Cách hoạt động**:
- **Confusion Matrix**: Ma trận trực quan hóa các lớp bị dự đoán nhầm.
- **Classification Report**: Tính toán các chỉ số chuyên sâu như Precision, Recall.
- **Visual Comparison**: Hiển thị trực tiếp ảnh mẫu kèm nhãn dự đoán để kiểm tra bằng mắt thường.
"""

import pandas as pd

# Lấy kết quả cuối cùng từ lịch sử huấn luyện
results = {
    'Metric': ['Final Training Loss', 'Final Validation Accuracy (%)'],
    'Model (Batch 32)': [f"{history_32['train_loss'][-1]:.4f}", f"{history_32['val_acc'][-1]:.2f}%"],
    'Model (Batch 64)': [f"{history_64['train_loss'][-1]:.4f}", f"{history_64['val_acc'][-1]:.2f}%"]
}

comparison_df = pd.DataFrame(results)
display(comparison_df)

print('\nNHẬN XÉT TỔNG QUAN:')
print(f"1. Độ chính xác: Cả hai model đều đạt kết quả cực cao (>99%).")
print(f"2. Hiệu suất: Model 64 có Validation Accuracy ({history_64['val_acc'][-1]:.2f}%) nhỉnh hơn một chút so với Model 32 ({history_32['val_acc'][-1]:.2f}%).")
print(f"3. Độ ổn định: Batch Size 64 thường giúp quá trình huấn luyện ổn định hơn và ít bị nhiễu gradient hơn.")